### ISSUE TITLE
Transfer to `xenserver` Github organisation?

### ISSUE THREAD

**Issue by ringods** [amfranz/terraform-provider-xenserver#9]
@benchalmers,

I am directing myself to you because you are listed as the first person in the `xenserver` Github organisation.

This codebase is the [Terraform](https://www.terraform.io/) provider for XenServer. This codebase was originally written by @amfranz but he indicated that he no longer has interest and time to work on it and is willing to transfer the repository:

https://github.com/amfranz/terraform-provider-xenserver/pull/3#issuecomment-327073966

Terraform has recently created a separate Github organisation for a number of Terraform providers: [`terraform-providers`](https://github.com/terraform-providers/). Hashicorp indicated somewhere (failed to find the source again) that this organisation will remain limited to the providers developed and maintained so far by Hashicorp and the contributors. But with the split came also the ability to have providers not in this specific setup. Work is in progress to let the core Terraform application download third-party providers not released via the Hashicorp infrastructure.

Which brings me to my request: I would very much like to see this codebase, together with peer repository [`go-xen-api-client`](https://github.com/amfranz/go-xen-api-client) be transferred to the `xenserver` Github organisation.

Are you the right person to direct my question to? If not, can you bring in the people who can?

Thank you,

Ringo (a sole contributor)

**Comment by benchalmers** [comment]
Hi Ringo,

I’m afraid I’m not the person to talk to (I’m specifically interested in the Windows PV Tools for the XenServer).  To get this added to the project, I would suggest you contact David.Cottingham@citrix.com – who will be able to give you a final answer.

However – whilst the xenserver project is tied to the interests of Citrix, in the case of the codebase in question, you might want to consider contacting the Xapi Project (which is part of the Linux Foundation’s xen project, and potentially more able to help you).  You can find their details athttps://www.xenproject.org/developers/teams/xapi.html – I would suggest you ask on their mailing list ( https://lists.xenproject.org/mailman/listinfo/xen-api ) in the first instance

Ben Chalmers

Sent from Mail for Windows 10

From: Ringo De Smet
Sent: Friday, September 22, 2017 1:06 PM
To: amfranz/terraform-provider-xenserver
Cc: Ben Chalmers; Mention
Subject: [amfranz/terraform-provider-xenserver] Transfer to `xenserver` Githuborganisation? (#9)

@benchalmers,
I am directing myself to you because you are listed as the first person in the xenserver Github organisation.
This codebase is the Terraform provider for XenServer. This codebase was originally written by @amfranz but he indicated that he no longer has interest and time to work on it and is willing to transfer the repository:
#3 (comment)
Terraform has recentely created a separate Github organisation for a number of Terraform providers: terraform-providers. Hashicorp indicated somewhere (failed to find the source again) that this organisation will remain limited on the providers developed and maintained so far by Hashicorp and the contributors. But with the split came also the ability to have providers not in this specific setup. Work is in progress to let the core Terraform application download third-party providers not released via the Hashicorp infrastructure.
Which brings me to my request: I would very much like to see this codebase, together with peer repository go-xen-api-client be transferred to the xenserver Github organisation.
Are you the right person to direct my question to? If not, can you bring in the people who can?
Thank you,
Ringo (a sole contributor)

**Comment by ringods** [comment]
@benchalmers thanks for your swift reply and the pointers provided. Indeed, the XAPI project might be a good place to put the governance of this project.

@jonludlam I see you listed at the top of the XAPI team list. Can you chime in on the request to transfer this codebase to the proper Github organisation? Given the input from @benchalmers, I guess this is the [`xapi-project`](https://github.com/xapi-project) organisation.

**Comment by ringods** [comment]
So far, none of my requests towards the Xen community lead to anything. Therefor, I will prepare first to take over the maintenance of this provider myself. PR #10 is to get my latest changes integrated first before transferring ownership of this repo to me.

**Comment by ringods** [comment]
@amfranz can you initiate the transfer of ownership to me please?

**Comment by amfranz** [comment]
I apologize, somehow I missed the initial notification.

Of course. Transfer underway. Take good care of the project :)
